import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CalendarClock, Copy, ExternalLink, Link2, MessageCircle, RefreshCw, ShieldCheck, UserRound, UsersRound, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { ErrorState, LoadingState } from '../components/LoadingState.js';
import { PageHeader } from '../components/PageHeader.js';
import { StatusPill } from '../components/StatusPill.js';
import { api, type PublicRecord } from '../lib/api.js';
import { dateTime, displayValue } from '../lib/format.js';
import { useAuth } from '../store/auth.js';

export function MeetingDetailPage() {
  const { meetingId } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const { user, hasPermission } = useAuth();
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [rescheduleOpen, setRescheduleOpen] = useState(false);
  const role = String(user?.role ?? '').toLowerCase().replace(/[\s-]+/g, '_'); const canManage = Boolean(hasPermission('meetings.update') || ['admin', 'hr', 'hr_manager', 'human_resources', 'human_resource', 'ceo', 'chief_executive_officer', 'chief_executive'].includes(role)); const canAttendance = Boolean(hasPermission('meetings.viewAttendance') || canManage);
  const query = useQuery({ queryKey: ['meeting', meetingId], enabled: Boolean(meetingId), queryFn: () => api<{ data: PublicRecord }>(`/meetings/${meetingId}`), refetchInterval: (current) => { const fields = current.state.data?.data.fields; const pending = String(fields?.status ?? '') === 'creating' && !String(fields?.google_meet_link ?? '').trim(); return pending ? 5_000 : false; } });
  if (query.isPending) return <LoadingState label="Loading meeting…" />; if (query.isError) return <ErrorState message={query.error.message} onRetry={() => void query.refetch()} />;
  const meeting = query.data.data; const fields = meeting.fields; const link = String(fields.google_meet_link ?? fields.meeting_link ?? '').trim(); const invitees = arrayObjects(fields.invitees); const participants = arrayObjects(fields.participants); const absent = arrayObjects(fields.absent_invitees);
  const refresh = async () => { await query.refetch(); await client.invalidateQueries({ queryKey: ['meetings'] }); await client.invalidateQueries({ queryKey: ['ceo-summary'] }); };
  const copyLink = async () => { if (!link) return; await navigator.clipboard?.writeText(link); };
  const runAction = async (action: string, request: () => Promise<unknown>) => { setBusy(action); setError(null); try { await request(); await refresh(); } catch (problem) { setError(problem instanceof Error ? problem.message : 'The meeting action could not be completed.'); } finally { setBusy(null); } };
  const cancel = () => { const reason = window.prompt('Why is this meeting being cancelled?'); if (!reason?.trim()) return; void runAction('cancel', () => api(`/meetings/${meetingId}/cancel`, { method: 'POST', body: JSON.stringify({ reason }) })); };
  const resend = () => { if (!window.confirm('Send meeting details to all CRM invitees again?')) return; void runAction('notify', () => api(`/meetings/${meetingId}/send-notification`, { method: 'POST' })); };
  const sync = () => void runAction('sync', () => api(`/meetings/${meetingId}/sync-attendance`, { method: 'POST' }));
  return <>
    <PageHeader eyebrow="MEETING WORKSPACE" title={String(fields.title ?? fields.name ?? 'Meeting')} description="Calendar event, Meet access, invitees and attendance are retained together." actions={<><button className="button button--secondary" type="button" onClick={() => navigate('/data/meetings')}><ArrowLeft size={16} /> Back to meetings</button>{canManage && <button className="button button--secondary" type="button" onClick={() => setRescheduleOpen(true)} disabled={Boolean(busy)}><CalendarClock size={16} /> Reschedule</button>}</>} />
    {error && <p className="form-error meeting-inline-error" role="alert">{error}</p>}
    {String(fields.google_meet_error ?? '').trim() && <p className="form-error meeting-inline-error" role="alert">{String(fields.google_meet_error)}</p>}
    <section className="content-card meeting-detail-hero"><div><p className="eyebrow">STATUS</p><StatusPill value={fields.status ?? 'scheduled'} /></div><div><p className="eyebrow">WHEN</p><strong>{dateTime(fields.scheduled_start ?? fields.meeting_date ?? fields.start_at)}</strong><span>{fields.scheduled_end ? `Ends ${dateTime(fields.scheduled_end)}` : 'End time not recorded'}</span></div><div><p className="eyebrow">ORGANIZER</p><strong><UserRound size={15} /> #{String(fields.organizer_id ?? fields.created_by ?? '—')}</strong></div><div className="meeting-detail-hero__actions">{link ? <><a className="button" href={link} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Join Google Meet</a><button className="button button--secondary" type="button" onClick={() => void copyLink()}><Copy size={15} /> Copy link</button></> : <span className="meeting-pending"><RefreshCw size={15} /> Meet link is being generated</span>}</div></section>
    <section className="meeting-detail-grid"><article className="content-card meeting-detail-panel"><div className="card-heading"><div><p className="eyebrow">INVITATIONS</p><h2>Invitees ({invitees.length})</h2></div><UsersRound size={19} /></div>{invitees.length ? <div className="meeting-people-list">{invitees.map((person, index) => <div key={`${String(person.crm_user ?? person.email)}-${index}`}><span className="meeting-person-avatar">{String(person.display_name ?? person.email ?? '?').slice(0, 1).toUpperCase()}</span><span><strong>{String(person.display_name ?? person.email ?? 'Invitee')}</strong><small>{String(person.email ?? '')}</small></span><StatusPill value={person.attendance_status ?? person.invitation_status ?? 'invited'} /></div>)}</div> : <p className="muted-copy">No CRM invitees were selected. {arrayObjects(fields.external_invitees).length ? `${arrayObjects(fields.external_invitees).length} external guest address(es) were sent through Google.` : ''}</p>}</article><article className="content-card meeting-detail-panel"><div className="card-heading"><div><p className="eyebrow">MEETING INFORMATION</p><h2>Agenda & context</h2></div><Link2 size={19} /></div><dl className="meeting-detail-list"><div><dt>Description</dt><dd>{displayValue(fields.description)}</dd></div><div><dt>Agenda</dt><dd>{displayValue(fields.agenda)}</dd></div><div><dt>Timezone</dt><dd>{displayValue(fields.timezone)}</dd></div><div><dt>Related CRM record</dt><dd>{fields.related_entity_type ? `${String(fields.related_entity_type)} #${String(fields.related_entity_id ?? '—')}` : 'None'}</dd></div></dl></article></section>
    <section className="meeting-detail-grid"><article className="content-card meeting-detail-panel"><div className="card-heading"><div><p className="eyebrow">ATTENDANCE</p><h2>Participants ({participants.length})</h2></div><ShieldCheck size={19} /></div>{canAttendance ? <>{participants.length ? <div className="meeting-participant-table"><div className="meeting-participant-head"><span>Participant</span><span>Status</span><span>Total time</span></div>{participants.map((person, index) => <div className="meeting-participant-row" key={`${String(person.email ?? person.google_participant_resource)}-${index}`}><span><strong>{String(person.display_name ?? person.email ?? 'Unidentified guest')}</strong><small>{String(person.email ?? 'Anonymous or unverified guest')}</small></span><StatusPill value={person.attendance_status ?? 'attended'} /><span>{formatDuration(person.total_duration_seconds)}</span></div>)}</div> : <p className="muted-copy">Attendance is not synchronized yet.</p>}{absent.length > 0 && <div className="meeting-absent"><strong>Absent invitees ({absent.length})</strong>{absent.map((person, index) => <span key={`${String(person.email)}-${index}`}>{String(person.display_name ?? person.email ?? 'Invitee')}</span>)}</div>}</> : <p className="muted-copy">Attendance details are restricted to authorised meeting managers.</p>}</article><article className="content-card meeting-detail-panel meeting-detail-actions"><div className="card-heading"><div><p className="eyebrow">WORKFLOW</p><h2>Meeting actions</h2></div><MessageCircle size={19} /></div><p className="muted-copy">Join/leave information may be recorded in the CRM. Recording and transcription are never started automatically.</p>{canAttendance && <button className="button button--secondary" type="button" disabled={Boolean(busy)} onClick={sync}><RefreshCw size={15} /> {busy === 'sync' ? 'Syncing attendance…' : 'Sync attendance'}</button>}{canManage && <><button className="button button--secondary" type="button" disabled={Boolean(busy) || !link} onClick={resend}><MessageCircle size={15} /> {busy === 'notify' ? 'Sending…' : 'Resend invitations'}</button><button className="button button--danger" type="button" disabled={Boolean(busy)} onClick={cancel}><X size={15} /> Cancel meeting</button></>}</article></section>
    {rescheduleOpen && <RescheduleDialog meetingId={meetingId ?? ''} fields={fields} onClose={() => setRescheduleOpen(false)} onSaved={async () => { setRescheduleOpen(false); await refresh(); }} />}
  </>;
}

function RescheduleDialog({ meetingId, fields, onClose, onSaved }: { meetingId: string; fields: Record<string, unknown>; onClose: () => void; onSaved: () => Promise<void> }) {
  const toLocal = (value: unknown) => { const parsed = new Date(String(value ?? '')); if (Number.isNaN(parsed.valueOf())) return ''; const offset = parsed.getTimezoneOffset() * 60_000; return new Date(parsed.getTime() - offset).toISOString().slice(0, 16); };
  const [start, setStart] = useState(toLocal(fields.scheduled_start)); const [end, setEnd] = useState(toLocal(fields.scheduled_end)); const [timezone, setTimezone] = useState(String(fields.timezone ?? 'Asia/Kolkata')); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await api(`/meetings/${meetingId}/reschedule`, { method: 'POST', body: JSON.stringify({ scheduledStart: new Date(start).toISOString(), scheduledEnd: new Date(end).toISOString(), timezone }) }); await onSaved(); } catch (problem) { setError(problem instanceof Error ? problem.message : 'Could not reschedule the meeting.'); } finally { setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Reschedule meeting" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">MEETING WORKSPACE</p><h2>Reschedule meeting</h2></div><button className="icon-button" type="button" onClick={onClose} aria-label="Close"><X size={19} /></button></div><form onSubmit={(event) => void submit(event)}><div className="form-grid"><label className="field"><span>Start *</span><input type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} required /></label><label className="field"><span>End *</span><input type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} required /></label><label className="field field--wide"><span>Timezone</span><input value={timezone} onChange={(event) => setTimezone(event.target.value)} required /></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button" type="submit" disabled={saving}>{saving ? 'Updating…' : 'Save new time'}</button></div></form></section></div>;
}

function arrayObjects(value: unknown): Array<Record<string, unknown>> { return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object')) : []; }
function formatDuration(value: unknown): string { const seconds = Number(value); if (!Number.isFinite(seconds) || seconds <= 0) return '—'; const minutes = Math.round(seconds / 60); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; }
