import { ArrowLeft, ExternalLink, Mail, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PublicSiteFooter, PublicSiteHeader } from '../components/PublicSiteHeader.js';

export function PrivacyPolicyPage() {
  return <div className="public-page public-policy-page">
    <div className="public-shell">
      <PublicSiteHeader active="privacy" />
      <main className="public-policy-main">
        <Link className="public-back-link" to="/"><ArrowLeft size={15} /> Back to KAKI CRM</Link>
        <header className="public-policy-header"><div className="public-policy-icon"><ShieldCheck size={26} /></div><p className="public-eyebrow">KAKI CRM PRIVACY POLICY</p><h1>Privacy, explained clearly.</h1><p>How M/s Chishikaki Creative Solutions (OPC) Private Limited collects, uses, stores and protects information when you visit or use KAKI CRM.</p><div className="public-policy-meta"><span>Effective: 2 September 2026</span><span>Last updated: 2 September 2026</span></div></header>

        <article className="public-policy-content">
          <section><h2>1. Who operates KAKI CRM</h2><p>KAKI CRM is a business operations and customer relationship management application operated by <strong>M/s Chishikaki Creative Solutions (OPC) Private Limited</strong> (“we”, “us” or “our”). Our office is at 132 B Darogapathar, Dimapur, Nagaland, India. For privacy questions, contact <a href="mailto:kaki.helps.brands@gmail.com">kaki.helps.brands@gmail.com</a> or call +91 88374 02472.</p></section>
          <section><h2>2. Information we collect</h2><p>Depending on the features your organisation enables, KAKI CRM may process:</p><ul><li><strong>Account and identity data:</strong> name, work email, role, employee ID, date of birth, phone number, WhatsApp number, profile image, department and reporting relationships.</li><li><strong>Work records:</strong> tasks, status changes, daily updates, task chat, mentions, projects, teams, clients, leads, quotations, invoices, payments, expenses, meetings, calendar events, files and audit history.</li><li><strong>People and payroll data:</strong> attendance, working hours, breaks, overtime, leave, shifts, salary structures, payroll calculations and salary slips. Access is restricted by role and organisation permissions.</li><li><strong>Technical and security data:</strong> sign-in events, failed sign-ins, session information, request identifiers, browser/device details, approximate network information and security/audit events.</li><li><strong>Support and notification data:</strong> messages or requests you send us, notification delivery status and preferences, and the minimum information needed to deliver an enabled work alert.</li></ul></section>
          <section><h2>3. How we use information</h2><p>We use information to provide and secure KAKI CRM, including to authenticate accounts; show role-appropriate records; create, assign and track work; calculate attendance and payroll; generate invoices and reports; deliver in-app and approved WhatsApp notifications; send meeting invitations; provide search, audit, recovery and support features; detect abuse; maintain backups; and comply with legal or contractual duties. We do not sell personal information or use CRM records for targeted advertising.</p></section>
          <section><h2>4. Google API and Google Workspace data</h2><p>Google Workspace connection is optional and starts only when an authorised user chooses to connect it. KAKI CRM may request Google profile email/name for account identification, Google Calendar event access to create or synchronise meetings, and Google Meet conference creation to generate a meeting link. We use that information only for the requested meeting, calendar and attendance workflows.</p><p>OAuth access and refresh tokens are encrypted before storage and are never displayed in the application. We do not sell Google data, use it for advertising, use it to determine creditworthiness, or transfer it for unrelated purposes. KAKI CRM’s use and transfer of information received from Google APIs complies with the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including its Limited Use requirements. You can disconnect Google from the Meetings workspace or revoke access from your Google Account security settings; after disconnection, stored tokens are removed and future synchronisation stops.</p></section>
          <section><h2>5. WhatsApp and other service providers</h2><p>If your organisation enables task-assignment WhatsApp alerts, we send the assigned employee’s saved WhatsApp number and the six task-template values (assigner, title, description, status, priority and due date) to Fast2SMS for delivery through the approved utility template. We do not send attachments through that task template. We may use trusted hosting, database, file-storage, email, analytics or security providers to operate the service; they may process information only to provide their contracted service, protect the platform or meet legal obligations.</p></section>
          <section><h2>6. Sharing and access controls</h2><p>Your organisation controls who can see its CRM records. KAKI CRM enforces role-based permissions: employees receive only permitted or assigned work, HR and administrators manage the areas assigned to them, and executive access is limited to authorised CEO users. Confidential notes and sensitive payroll or financial records are not made visible to unauthorised people. We disclose information only to authorised organisation users, service providers acting on our instructions, when you request a connected integration, or when required to prevent harm, investigate abuse or comply with law.</p></section>
          <section><h2>7. Storage, retention and deletion</h2><p>Records are stored in the organisation’s configured MongoDB database and protected file storage. We keep account and work records while the organisation needs the service, or longer when required for accounting, tax, employment, dispute or security obligations. Archived records are recoverable through the recycle workflow rather than silently destroyed. When a Google integration is disconnected, its stored OAuth tokens are deleted. To request correction, export, account closure or deletion of information, contact us at <a href="mailto:kaki.helps.brands@gmail.com">kaki.helps.brands@gmail.com</a> with your name, organisation and the specific request. We may need to verify your identity and may retain limited records where law or legitimate security needs require it.</p></section>
          <section><h2>8. Security</h2><p>We use encrypted transport where the deployment is configured for HTTPS, password hashing, encrypted integration credentials, least-privilege route checks, rate limiting, access tokens with expiry, audit records and recoverable archives. No internet service can promise absolute security, so keep your password private, sign out of shared devices and tell your administrator promptly about suspected unauthorised access.</p></section>
          <section><h2>9. Cookies and local storage</h2><p>KAKI CRM uses essential browser storage for the signed-in access token, theme preference and limited interface state such as sidebar visibility. These items support authentication and the requested interface; we do not use them for cross-site advertising. Clearing browser storage signs you out of the current browser session.</p></section>
          <section><h2>10. Children and international use</h2><p>KAKI CRM is a business service and is not directed to children. Organisations are responsible for ensuring that their use of the service and the information they enter complies with applicable employment, privacy and data-protection laws. Service providers may process data in locations needed to operate the service, subject to contractual and security safeguards.</p></section>
          <section><h2>11. Changes to this policy</h2><p>We may update this policy when the application, integrations or legal requirements change. We will post the new effective date on this page. Material changes should be reviewed by your organisation before continued use.</p></section>
          <section className="public-policy-contact"><h2>12. Contact us</h2><p>Questions, access requests and privacy concerns can be sent to:</p><address><strong>M/s Chishikaki Creative Solutions (OPC) Private Limited</strong><br />132 B Darogapathar, Dimapur, Nagaland, India<br />Phone: +91 88374 02472<br /><a href="mailto:kaki.helps.brands@gmail.com"><Mail size={14} /> kaki.helps.brands@gmail.com</a></address><a className="public-policy-external" href="https://www.kakicrm.store/" target="_blank" rel="noreferrer">Visit the public KAKI CRM home page <ExternalLink size={14} /></a></section>
        </article>
      </main>
      <PublicSiteFooter />
    </div>
  </div>;
}
