import 'dotenv/config';
import path from 'node:path';
import { z } from 'zod';

const optionalEnvText = z.preprocess(
  (value) => typeof value === 'string' && !value.trim() ? undefined : value,
  z.string().trim().min(1).optional()
);

const schema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().positive().default(4000),
  HOST: z.string().trim().min(1).default('127.0.0.1'),
  MONGODB_URI: z.string().min(1).default('mongodb://127.0.0.1:27017/kaki_crm_modern'),
  CORS_ORIGIN: z.string().min(1).default('http://localhost:5173'),
  // Public browser origin(s). The first valid origin is used for OAuth
  // callbacks and provider redirects; CORS_ORIGIN remains the compatibility
  // fallback for older deployments.
  APP_ORIGIN: optionalEnvText,
  JWT_ACCESS_SECRET: z.string().min(24).default('replace-with-a-long-random-access-secret'),
  JWT_ACCESS_TTL: z.string().min(2).default('8h'),
  UPLOAD_ROOT: z.string().min(1).default('./server/uploads'),
  // Uploaded media is stored in Atlas GridFS. Keep this stable so an
  // application redeploy can always find media created by earlier releases.
  MEDIA_GRIDFS_BUCKET: z.string().trim().min(1).default('kaki_uploads'),
  MAX_UPLOAD_MB: z.coerce.number().positive().max(100).default(25),

  // Disaster-recovery controls. Secrets are generated by the production
  // deployer and remain only in the protected production .env file.
  BACKUP_ROOT: z.string().min(1).default('/var/backups/kaki-crm'),
  BACKUP_ENGINE_PATH: optionalEnvText,
  BACKUP_ENCRYPTION_PASSPHRASE: optionalEnvText,
  BACKUP_LOCAL_RETENTION_COUNT: z.coerce.number().int().min(3).max(365).default(30),
  BACKUP_DRIVE_RETENTION_DAYS: z.coerce.number().int().min(7).max(3650).default(180),
  BACKUP_EXTRA_PATHS: optionalEnvText,
  BACKUP_MAX_UPLOAD_GB: z.coerce.number().positive().max(100).default(20),

  // Fast2SMS WhatsApp task-assignment notifications. The API key belongs only
  // in the deployment .env file and is never bundled with a release.
  FAST2SMS_API_KEY: optionalEnvText,
  FAST2SMS_WHATSAPP_API_KEY: optionalEnvText,
  // Optional stable encryption secret for administrator-managed integration
  // credentials. When omitted, the JWT access secret is used as a backwards-
  // compatible fallback. Keep this value stable after credentials are saved.
  SETTINGS_ENCRYPTION_SECRET: optionalEnvText,
  // Keep this secret stable so saved credential values remain decryptable
  // after application deployments and token secret rotations.
  CREDENTIAL_VAULT_ENCRYPTION_SECRET: optionalEnvText,
  // Dedicated, stable key for server-managed WhatsApp Business credentials.
  WHATSAPP_BUSINESS_ENCRYPTION_SECRET: optionalEnvText,
  WHATSAPP_GRAPH_API_VERSION: z.string().trim().regex(/^v\\d+\\.0$/).default('v25.0'),
  // Browser push notification credentials. Keep the private key only in the
  // Render environment; the public key is safe to expose to authenticated
  // clients when they opt in.
  PUSH_VAPID_PUBLIC_KEY: optionalEnvText,
  PUSH_VAPID_PRIVATE_KEY: optionalEnvText,
  PUSH_VAPID_SUBJECT: z.string().url().default('mailto:admin@kakicrm.com'),
  FAST2SMS_WHATSAPP_API_URL: z.string().url().default('https://www.fast2sms.com/dev/whatsapp'),
  FAST2SMS_WHATSAPP_TEMPLATE_NAME: z.string().trim().default('my_task'),
  FAST2SMS_WHATSAPP_MESSAGE_ID: z.string().trim().regex(/^\d+$/).default('30840'),
  FAST2SMS_WHATSAPP_PHONE_NUMBER_ID: z.string().trim().regex(/^\d+$/).default('1202480702956271'),
  FAST2SMS_WHATSAPP_SENDER_NUMBER: z.string().trim().default('+916009345739'),
  GOOGLE_CLIENT_ID: optionalEnvText,
  GOOGLE_CLIENT_SECRET: optionalEnvText,
  GOOGLE_OAUTH_REDIRECT_URI: optionalEnvText,
  GOOGLE_TOKEN_ENCRYPTION_KEY: optionalEnvText,
  GOOGLE_CLOUD_PROJECT_ID: optionalEnvText,
  GOOGLE_PUBSUB_TOPIC: optionalEnvText,
  GOOGLE_PUBSUB_SUBSCRIPTION: optionalEnvText,
  GOOGLE_WORKSPACE_EVENTS_CALLBACK_URL: optionalEnvText,
  // Optional shared verification tokens for provider callbacks. In a
  // production Google Pub/Sub deployment, prefer an authenticated push
  // subscription and keep this as an additional boundary where supported.
  GOOGLE_WORKSPACE_WEBHOOK_TOKEN: optionalEnvText,
  WHATSAPP_WEBHOOK_VERIFY_TOKEN: optionalEnvText,
  MEETING_ATTENDANCE_SYNC_ENABLED: z.coerce.boolean().default(true),
  MEETING_REALTIME_EVENTS_ENABLED: z.coerce.boolean().default(false),
  MEETING_LATE_AFTER_MINUTES: z.coerce.number().int().min(0).max(240).default(10),
  MEETING_MINIMUM_ATTENDANCE_PERCENT: z.coerce.number().min(0).max(100).default(50),
  MEETING_LEFT_EARLY_BEFORE_MINUTES: z.coerce.number().int().min(0).max(240).default(10),
  WHATSAPP_GROUPS_ENABLED: z.coerce.boolean().default(false),
  WHATSAPP_MEETING_TEMPLATE_NAME: optionalEnvText,
  WHATSAPP_MEETING_RESCHEDULED_TEMPLATE_NAME: optionalEnvText,
  WHATSAPP_MEETING_CANCELLED_TEMPLATE_NAME: optionalEnvText,
  WHATSAPP_MEETING_REMINDER_TEMPLATE_NAME: optionalEnvText
});

const parsed = schema.safeParse(process.env);

if (!parsed.success) {
  throw new Error(`Invalid environment: ${parsed.error.issues.map((issue) => issue.message).join(', ')}`);
}

const values = parsed.data;

export const env = {
  ...values,
  uploadRoot: path.resolve(process.cwd(), values.UPLOAD_ROOT),
  backupRoot: path.resolve(values.BACKUP_ROOT),
  backupEnginePath: path.resolve(values.BACKUP_ENGINE_PATH ?? path.join(process.cwd(), 'scripts/backup-engine.sh')),
  maxUploadBytes: values.MAX_UPLOAD_MB * 1024 * 1024
} as const;
